# This property specifies whether or not VisTool Web Service will use Spring Security.
vistool.security.enabled=true

# This property specifies the CORS Allowed Origin header value.
vistool.security.cors.allowed.origin=https://vistool-prod.jhuapl.edu:*

# The following properties specify the primary datasource configuration used for VisTool model objects.
vistool.datasource.jdbc-url=jdbc:mysql://sdint-mysql.jhuapl.edu:3306/vistool
vistool.datasource.username=vistool
vistool.datasource.password=ENC(Sih7jK91QB/rYZv55C3eFcedplOQ3c9CQxTGyloPOXCc2s0RNjTMMq3k5sQzcGWg)
vistool.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
vistool.datasource.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

vistool.svc-account-ldap.enabled=false

denodo.url=https://denodo.jhuapl.edu:9443/server