# This property specifies whether or not VisTool Web Service will use Spring Security.
vistool.security.enabled=true

# This property specifies the CORS Allowed Origin header value.
vistool.security.cors.allowed.origin=https://vistool-test.jhuapl.edu:*

# The following properties specify the primary datasource configuration used for VisTool model objects.
vistool.datasource.jdbc-url=jdbc:mysql://vistool-test:3306/vistool
vistool.datasource.username=vistool
vistool.datasource.password=ENC(wOdcIJtES3xIsbX53htqevvg1uiiFUwg60RDZk5OKEx3Xc0lC9vzrlg+S4caw2QJ8dTB97qtmHCZBZZESINZAQ==)
vistool.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
vistool.datasource.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

vistool.svc-account-ldap.enabled=false

denodo.url=https://denodotest.jhuapl.edu:9443/server