# This property sets the active profile specified during the build.
spring.profiles.active=@activatedProperties@

# This property disables the Spring Boot banner in the log file.
spring.main.banner-mode=off

# This property specifies the log file directory.
logging.file.path=./logs/

logging.level.edu.jhuapl.sd.sig.vistool.vistoolwebservice.*=INFO

# These properties specify the APL mail server information.
spring.mail.host=mail.jhuapl.edu
spring.mail.properties.mail.smtp.port=25

# These properties specify the Denodo credentials VisTool Web Service uses.
denodo.username=svc-dv-vistool
denodo.password=ENC(hFonLR5PvAcd32Wdc7n53Nce4nRot7DXXbK197Q0t3lwzgaaEhAKTAIKdgpv0XbGkv/pcTS9nKBja53M8TwG1Q==)

# The following properties specify the secondary datasource configuration used for Denodo model objects.
denodo.datasource.jdbc-url=jdbc:h2:mem:denodo;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
denodo.datasource.driver-class-name=org.h2.Driver
denodo.datasource.hibernate.dialect=org.hibernate.dialect.H2Dialect

# set scheduled task rate in milliseconds (30 minutes by default)
denodo.scheduled.task.fixed.rate=1800000
denodo.scheduled.task.wo-ops-data-refresh.fixed.rate=0 0 0/12 * * ?

# denodo request timeout in seconds (10 minutes by default)
denodo.request.timeout=600

# This property specifies the environment variable used by JASYPT to decrypt encrypted properties.
jasypt.encryptor.password=${VISTOOL_SECRET}

# This property specifies whether or not Vistool Web Service will run Denodo integration tests during builds.
testing.integration.denodo=false

# This property determines the default session duration to 24 hours
server.servlet.session.timeout=24h

# These properties set the credentials for the LDAP service account.
ldap.url=ldaps://ldap.jhuapl.edu:636
ldap.query.base=DC=dom1,DC=jhuapl,DC=edu
ldap.query.userAccountAttribute=sAMAccountName
ldap.svcaccount.username=svc-ldap-ist
ldap.svcaccount.password=ENC(eW02SAKWkkqGYIqZ0h64iQzZX1SMv/mCFKJ6rEmj/nsXYGBJtZhPMQNyPc8vK7tj)
