# This property specifies whether or not VisTool Web Service will use Spring Security.
vistool.security.enabled=true

# This property specifies the CORS Allowed Origin header value.
vistool.security.cors.allowed.origin=https://localhost:*

# The following properties specify the Spring Boot HTTPS configuration.
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:vistool.p12
server.ssl.key-store-password=ENC(9QW0i76MS0ptiU//oLZq/b0CgJd688qbJfdAfTY13G8CorsULUxsXV0PZUFvFL67x8ifgyad5PUHavQ5axjiOA==)

# The following properties specify the primary datasource configuration used for VisTool model objects.
vistool.datasource.jdbc-url=jdbc:mysql://${VISTOOL_DATABASE_HOST}:${VISTOOL_DATABASE_PORT}/${VISTOOL_DATABASE}
vistool.datasource.username=${VISTOOL_DATABASE_USER}
vistool.datasource.password=${VISTOOL_DATABASE_PASSWORD}
vistool.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
vistool.datasource.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# These properties configure the Spring Boot's embedded Tomcat server file upload settings.
spring.servlet.multipart.max-file-size=10MB
server.tomcat.max-http-form-post-size=100000000
server.tomcat.max-swallow-size=100000000

vistool.svc-account-ldap.enabled=true

denodo.url=https://denododev.jhuapl.edu:9443/server