CREATE USER '{{VISTOOL_DATABASE_USER}}'@'%' IDENTIFIED BY '{{VISTOOL_DATABASE_PASSWORD}}';
GRANT CREATE ON *.* TO '{{VISTOOL_DATABASE_USER}}'@'%';
GRANT ALL PRIVILEGES ON vistool.* TO '{{VISTOOL_DATABASE_USER}}'@'%';
FLUSH PRIVILEGES;