FROM mysql:8.0

# Initalize environmental variables
ARG VISTOOL_DATABASE_HOST
ARG VISTOOL_DATABASE_USER
ARG VISTOOL_DATABASE_PASSWORD
ARG VISTOOL_DATABASE_PORT

ENV VISTOOL_DATABASE_HOST=$VISTOOL_DATABASE_HOST
ENV VISTOOL_DATABASE_USER=$VISTOOL_DATABASE_USER
ENV VISTOOL_DATABASE_PASSWORD=$VISTOOL_DATABASE_PASSWORD
ENV VISTOOL_DATABASE_PORT=$VISTOOL_DATABASE_PORT

ENV MYSQL_DATABASE=$VISTOOL_DATABASE
ENV MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PWD

# Initialize the database
COPY ./db_scripts .
COPY ./docker/.env .
COPY ./docker/db-updater.sh .
COPY ./docker/create_triggers.sql .
ENTRYPOINT sh db-updater.sh
