package edu.jhuapl.sd.sig.vistool.vistoolwebservice.model.denodo;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.annotations.SerializedName;
import lombok.Data;

import javax.persistence.Entity;
import javax.persistence.Id;
import java.io.Serializable;
import java.util.Date;

import static edu.jhuapl.sd.sig.vistool.vistoolwebservice.constants.denodo.DimHRPersonConstants.*;
import static edu.jhuapl.sd.sig.vistool.vistoolwebservice.util.VistoolUtilities.YEAR_MONTH_DAY_FORMAT;

@Data
@Entity
public class DimHRPerson implements Serializable {
    @SerializedName(APL_SPONSOR_FULL_NAME) private String aplSponsorFullName;
    @SerializedName(APL_SPONSOR_NUMBER) private String aplSponsorNumber;
    @SerializedName(ASSIGNED_FACILITY_CODE) private String assignedFacilityCode;
    @SerializedName(ASSIGNED_FACILITY_DESCRIPTION) private String assignedFacilityDescription;
    @SerializedName(BRANCH_CODE) private String branchCode;
    @SerializedName(COMPANY_NAME) private String companyName;
    @SerializedName(DEPARTMENT_CODE) private String deptID;
    @SerializedName(DEPARTMENT_NAME) private String deptName;
    @SerializedName(DIRECT_SUPERVISOR_KEY) private Integer directSupervisorKey;
    @SerializedName(DIRECT_SUPERVISOR_NUMBER) private String directSupervisorNumber;
    @SerializedName(EMAIL_ID) private String emailId;
    @SerializedName(FACILITY_CODE) private String facilityCode;
    @SerializedName(FACILITY_DESCRIPTION) private String facilityDescription;
    @SerializedName(FACILITY_UPDATE_DATE) private Date facilityUpdateDate;
    @SerializedName(FAIR_LABOR_STANDARDS_ACT_STATUS_CODE) private String flsaStatusCode;
    @SerializedName(FAIR_LABOR_STANDARDS_ACT_STATUS_DESCRIPTION) private String flsaStatusDescription;
    @SerializedName(FIRST_NAME) private String firstName;
    @SerializedName(FULL_LAB_PHONE_1_NUMBER) private String fullLabPhone1Num;
    @SerializedName(FULL_LAB_PHONE_2_NUMBER) private String fullLabPhone2Num;
    @SerializedName(FULL_NAME) private String fullName;
    @SerializedName(FULL_OR_PART_TIME_IND) private String fullPartInd;
    @SerializedName(GROUP_CODE) private String groupCode;
    @SerializedName(GROUP_NAME) private String groupName;
    @SerializedName(GROUP_SUPERVISOR_NUMBER) private String groupSupervisorNumber;
    @SerializedName(GROUP_SUPERVISOR_FULL_NAME) private String groupSupervisorFullName;
    @SerializedName(GROUP_SUPERVISOR_LAB_PHONE_1_EXT) private String groupSupervisorLabPhone1Ext;
    @SerializedName(HIGHEST_DEGREE_FIELD_CODE) private String highestDegreeFieldCode;
    @SerializedName(HIGHEST_DEGREE_FIELD_DESCRIPTION) private String highestDegreeFieldDescription;
    @SerializedName(HIGHEST_EDUCATION_CODE) private String highestEducationCode;
    @SerializedName(HIGHEST_EDUCATION_DESCRIPTION) private String highestEducationDescription;
    @SerializedName(HIRE_DATE) private Date hireDate;
    @SerializedName(JHED_ID) private String jhedID;
    @SerializedName(JHU_INSTRUCTOR_FLAG) private String jhuInstructorFlag;
    @SerializedName(JOB_CLASS_DESCRIPTION) private String jobClass;
    @SerializedName(JOB_DESIGNATION_CODE) private String jobDesignationCode;
    @SerializedName(JOB_DESIGNATION_DESCRIPTION) private String jobDesignationDescription;
    @SerializedName(LAB_PHONE_1_EXT) private String labPhone1Ext;
    @SerializedName(LAB_PHONE_2_EXT) private String labPhone2Ext;
    @SerializedName(LABOR_ALLOCATION_CODE) private String laborAllocationCode;
    @SerializedName(LABOR_ALLOCATION_NAME) private String laborAllocationName;
    @SerializedName(LABOR_CLASS_CODE) private String laborClassCode;
    @SerializedName(LABOR_CLASS_DESCRIPTION) private String laborClassDescription;
    @SerializedName(LAST_NAME) private String lastName;
    @SerializedName(MAIL_BUILDING_NUMBER) private String mailBuildingNumber;
    @SerializedName(MAIL_BUILDING_WING_CODE) private String mailBuildingWingCode;
    @SerializedName(MAIL_LOCATION_DISPLAY_ID) private String mailLocationDisplayId;
    @SerializedName(MAIL_NONSTANDARD_LOCATION_CODE) private String mailNonstandardLocationCode;
    @SerializedName(MAIL_NONSTANDARD_LOCATION_NAME) private String mailNonstandardLocationName;
    @SerializedName(MAIL_ROOM_NUMBER) private String mailRoomNumber;
    @SerializedName(MAIL_ROOM_SUB_CODE) private String mailRoomSubCode;
    @SerializedName(MIDDLE_NAME) private String middleName;
    @SerializedName(MOBILE_NUMBER) private String mobileNumber;
    @SerializedName(OCCUPY_SPACE_FLAG) private String occupySpaceFlag;
    @SerializedName(OFFICE_BUILDING_NUMBER) private String officeBuildingNumber;
    @SerializedName(OFFICE_BUILDING_WING_CODE) private String officeBuildingWingCode;
    @SerializedName(OFFICE_LOCATION_DISPLAY_ID) private String officeLocationDisplayId;
    @SerializedName(OFFICE_NONSTANDARD_LOCATION_CODE) private String officeNonstandardLocationCode;
    @SerializedName(OFFICE_NONSTANDARD_LOCATION_NAME) private String officeNonstandardLocationName;
    @SerializedName(OFFICE_ROOM_NUMBER) private String officeRoomNumber;
    @SerializedName(OFFICE_ROOM_SUB_CODE) private String officeRoomSubCode;
    @SerializedName(OFFSITE_FLAG) private String offsiteCode;
    @SerializedName(ONCALL) private String oncall;
    @SerializedName(ORGANIZATION_CODE) private String organizationCode;
    @SerializedName(ORGANZATION_NAME) private String organizationName;
    @SerializedName(PERSON_KEY) private Integer personKey;
    @Id @SerializedName(PERSON_NUMBER) private String personNumber;
    @SerializedName(PERSON_STATUS_CODE) private String personStatusCode;
    @SerializedName(PERSON_STATUS_NAME) private String personStatusName;
    @SerializedName(PERSON_SUB_STATUS_CODE) private String personSubStatusCode;
    @SerializedName(PERSON_SUB_STATUS_NAME) private String personSubStatusName;
    @SerializedName(PERSON_SUBTYPE_CODE) private String personSubTypeCode;
    @SerializedName(PERSON_SUBTYPE_NAME) private String personSubTypeName;
    @SerializedName(PERSON_TYPE_CODE) private String personTypeCode;
    @SerializedName(POSITION_MANAGEMENT_DIRECT_SUPERVISOR_KEY) private Integer positionManagementDirectSupervisorKey;
    @SerializedName(POSITION_MANAGEMENT_DIRECT_SUPERVISOR_NUMBER) private String positionManagementDirectSupervisorNumber;
    @SerializedName(PREFERRED_FIRST_NAME) private String preferredFirstName;
    @SerializedName(PREFERRED_FULL_NAME) private String preferredFullName;
    @SerializedName(PREFERRED_LAST_NAME) private String preferredLastName;
    @SerializedName(PREFIX_NAME) private String prefixName;
    @SerializedName(PROGRAM_LEVEL_DESCRIPTION) private String programLevelDescription;
    @SerializedName(PROGRAM_LEVEL_NUMBER) private String programLevelNumber;
    @SerializedName(REGULAR_OR_TEMP_EMPLOYEE) private String regOrTempEmployee;
    @SerializedName(REPORT_TO_VACANT_FLAG) private String reportToVacantFlag;
    @SerializedName(SECTION_CODE) private String sectionCode;
    @SerializedName(SECTION_NAME) private String sectionName;
    @SerializedName(SECTION_SUPERVISOR_NUMBER) private String sectionSupervisorNumber;
    @SerializedName(SECTION_SUPERVISOR_FULL_NAME) private String sectionSupervisorFullName;
    @SerializedName(STAFF_LEVEL_CODE) private String staffLevelCode;
    @SerializedName(STAFF_LEVEL_DESCRIPTION) private String staffLevelDescription;
    @SerializedName(STAFF_LEVEL_NUMBER) private String staffLevelNumber;
    @SerializedName(SUFFIX_NAME) private String suffix;
    @SerializedName(SUPERVISOR_ACTING_FLAG) private String supervisorActingFlag;
    @SerializedName(SUPERVISOR_KEY) private Integer supervisorKey;
    @SerializedName(SUPERVISOR_LEVEL_CODE) private String supervisorLevelCode;
    @SerializedName(SUPERVISOR_LEVEL_LONG_NAME) private String supervisorLevelLongName;
    @SerializedName(SUPERVISOR_LEVEL_NAME) private String supervisorLevelName;
    @SerializedName(SUPERVISOR_LEVEL_NUMBER) private String supervisorLevelNumber;
    @SerializedName(SUPERVISOR_NUMBER) private String supervisorNumber;
    @SerializedName(SUPERVISOR_RANK_NUMBER) private Integer supervisorRankNumber;
    @SerializedName(TECHNICAL_OR_ADMIN_CODE) private String technicalOrAdminCode;
    @SerializedName(TECHNICAL_OR_ADMIN_DESCRIPTION) private String technicalOrAdminDescription;
    @SerializedName(TERMINATION_DATE) private Date terminationDate;
    @SerializedName(UPDATE_DATETIME) private Date lastUpdatedDate;
    @SerializedName(USER_ID) private String userId;
    @SerializedName(WORK_ARRANGEMENT) private String workArrangement;
    @SerializedName(WORK_PERCENT) private Integer workPercent;

    public final static transient Gson SERIALIZER = new GsonBuilder().serializeNulls().setDateFormat(YEAR_MONTH_DAY_FORMAT).create();
}
